apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backstage
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
spec:
  type: openapi
  owner: Joao Antunes
  lifecycle: experimental
