apiVersion: backstage.io/v1alpha1
kind: .Net 6.0
metadata:
  name: PrbAppConsignado
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  links:
    - title: Hom
      url: https://prbappconsignado-webapi-bff-app-consignado-hom.apps.cluster.h.pbtech.net.br/swagger/index.html
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
spec:
  type: .Net 6.0
  owner: Joao Antunes
  lifecycle: experimental
